export default {
  "ACUR": "ACURA",
  "ALFA": "ALFA ROMEO",
  "AUDI": "AUDI",
  "BUIC": "BUICK",
  "BMW": "BMW",
  "CADI": "CADILLAC",
  "CHEV": "CHEVROLET",
  "CHRY": "CHRYSLER",
  "DODG": "DODGE",
  "FIAT": "FIAT",
  "FORD": "FORD",
  "FRHT": "FREIGHTLINER",
  "GM": "GMC",
  "GMC": "GMC",
  "HD": "HARLEY DAVIDSON",
  "HOND": "HONDA",
  "HUMM": "HUMMER",
  "HYUN": "HYUNDAI",
  "INFI": "INFINITI",
  "JAGU": "JAGUAR",
  "JEEP": "JEEP",
  "KIA": "KIA",
  "LEXS": "LEXUS",
  "LINC": "LINCOLN",
  "LNDR": "LAND ROVER",
  "MAZD": "MAZDA",
  "MERC": "MERCURY",
  "MERZ": "MERCEDES-BENZ",
  "MNNI": "MINI",
  "MITS": "MITSUBISHI",
  "NISS": "NISSAN",
  "OLDS": "OLDSMOBILE",
  "PONI": "PONTIAC",
  "PONT": "PONTIAC",
  "PORS": "PORSCHE",
  "PROW": "PROWLER",
  "RAM": "RAM",
  "ROL": "ROLLS ROYCE",
  "SAA": "SAAB",
  "SATR": "SATURN",
  "SMRT": "SMART",
  "STRN": "SATURN",
  "SUBA": "SUBARU",
  "SUZI": "SUZUKI",
  "TESL": "TESLA",
  "TOYO": "TOYOTA",
  "TOYT": "TOYOTA",
  "TRIU": "TRIUMPH",
  "VOLK": "VOLKSWAGEN",
  "VOLV": "VOLVO",
  "WSTR": "WESTERN STAR"
}
